#
# Any copyright is dedicated to the Public Domain.
#
# Copyright 2021 William Swartzendruber
#
# SPDX-License-Identifier: CC0-1.0
#

[workspace]

members = [
    "pq2hlg",
    "pqstat",
    "dsp",
]
