#
# Any copyright is dedicated to the Public Domain.
#
# Copyright 2021 William Swartzendruber
#
# SPDX-License-Identifier: CC0-1.0
#

[package]
name = "dsp"
version = "0.3.0"
authors = ["William Swartzendruber <wswartzendruber@gmail.com>"]
edition = "2018"
license = "MPL-2.0"

[dev-dependencies]
assert_approx_eq = "1.1.0"
